name: Build kernel
on:
  # Triggers the workflow on push or pull request events but only for the "mainline-test" branch
  push:
    branches: [ "main" ]

jobs:
  main:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - name: Maximizing build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          
      - name: Generating release tag and setting prerelease
        id: tag
        run: |
          if echo ${{ github.event.head_commit.message }} | grep -c "dev"
          then
            echo "::set-output name=release_tag::dev-build"
            echo "::set-output name=release_type::true"
          else
            echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"
            echo "::set-output name=release_type::false"
          fi
      
      - name: Preparing Changelog        
        run: |
          echo 'CHNGLG<<EOF' >> $GITHUB_ENV
          cat changelog.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      
      - name: Building the standard Kernel
        run: bash build.sh
      
      - name: Deleting old dev release
        if: "contains(github.event.head_commit.message, 'dev')"
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: dev-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Creating new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Kernel build - ${{ github.event.head_commit.message }}
          prerelease: ${{ steps.tag.outputs.release_type }}
          body: |
            Changelog:
            ```
            ${{ env.CHNGLG }}
            ```
            Kernel Delivery System - Triggered by ${{ github.sha }} at ${{ github.event.repository.updated_at }}
          files: |
            bzImage
            bzImage.signed
            modules.tar.xz
            headers.tar.xz
